/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package EderEsquivel.bison_system.swing;

import EderEsquivel.bison_system.model.DatosGenerales;
import static EderEsquivel.bison_system.model.DatosGenerales.obtenerEjerciciosPorZona;
import EderEsquivel.bison_system.model.Ejercicios;
import EderEsquivel.bison_system.model.Musculos;
import EderEsquivel.bison_system.model.ZonasAnatomicas;
import java.awt.Color;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author edere
 */
public class CategoriasEjercicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form CategoriasEjercicios
     */
    public CategoriasEjercicios() {
        initComponents();
        for (ZonasAnatomicas zona : DatosGenerales.zonasAnatomicasMap.values()) {
            cbxZonas.addItem(zona.getNombre_zona());
        }
        cbxZonas.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxZonas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnVerEjercicios = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Zonas Anatomicas");

        btnVerEjercicios.setText("Ver ejercicios");
        btnVerEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEjerciciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxZonas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(142, 142, 142))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnVerEjercicios)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnVerEjercicios)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEjerciciosActionPerformed
        // TODO add your handling code here:
        int idZonaSelecionada=cbxZonas.getSelectedIndex()+1;
        listaEjercicios=DatosGenerales.obtenerEjerciciosPorZona(idZonaSelecionada);
        if(!listaEjercicios.isEmpty()){
            java.awt.Window ventanaPadre = javax.swing.SwingUtilities.getWindowAncestor(this);
            Ejercicio listEjercicios = new Ejercicio((Frame) ventanaPadre);
            listEjercicios.setLocationRelativeTo(this);
            listEjercicios.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "No seleccionaste una categoria",
                    "!Error!", JOptionPane.ERROR_MESSAGE);
        }
         
        
    }//GEN-LAST:event_btnVerEjerciciosActionPerformed

    public static List<Ejercicios> listaEjercicios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerEjercicios;
    private javax.swing.JComboBox<String> cbxZonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
