/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package EderEsquivel.bison_system.swing;

import EderEsquivel.bison_system.model.DatosGenerales;
import EderEsquivel.bison_system.model.Ejercicios;
import EderEsquivel.bison_system.model.ZonasAnatomicas;
import static EderEsquivel.bison_system.swing.CategoriasEjercicios.listaEjercicios;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edere
 */
public class Entrenamientos extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form Entrenamientos
     */
    public Entrenamientos() {
        initComponents();
        this.setResizable(false);
        for (ZonasAnatomicas zona : DatosGenerales.zonasAnatomicasMap.values()) {
            cbxCategoria.addItem(zona.getNombre_zona());
        }
        cbxCategoria.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxCategoria = new javax.swing.JComboBox<>();
        cbxEjercicio = new javax.swing.JComboBox<>();
        btnSC = new javax.swing.JButton();
        btnSE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEjerciciosS = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(java.awt.SystemColor.window);

        btnSC.setText("Seleccionar Categoria");
        btnSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSCActionPerformed(evt);
            }
        });

        btnSE.setText("Seleccionar Ejercicio");
        btnSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEActionPerformed(evt);
            }
        });

        TEjerciciosS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ejercicio", "Series"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TEjerciciosS);
        if (TEjerciciosS.getColumnModel().getColumnCount() > 0) {
            TEjerciciosS.getColumnModel().getColumn(0).setResizable(false);
            TEjerciciosS.getColumnModel().getColumn(1).setResizable(false);
        }

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSC))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSE)
                                    .addComponent(cbxEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnEliminar)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSE)
                    .addComponent(btnSC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSCActionPerformed
        // TODO add your handling code here:
        cbxEjercicio.removeAllItems();
        int idZonaSelecionada=cbxCategoria.getSelectedIndex()+1;
        listaEjercicios=DatosGenerales.obtenerEjerciciosPorZona(idZonaSelecionada);
        for (Ejercicios ejercicio : listaEjercicios) {
            cbxEjercicio.addItem(ejercicio.getNombre());
        }
        cbxEjercicio.setSelectedIndex(-1);
    }//GEN-LAST:event_btnSCActionPerformed

    private void btnSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEActionPerformed
        // TODO add your handling code here:
        String ejercicioSeleccionado = (String) cbxEjercicio.getSelectedItem();

        // Verificar si ya fue agregado
        boolean yaAgregado = false;
        for (Ejercicios ej : listaEjerciciosSeleccionados) {
            if (ej.getNombre().equals(ejercicioSeleccionado)) {
                yaAgregado = true;
                break;
            }
        }

        if (yaAgregado) {
            JOptionPane.showMessageDialog(this, "Este ejercicio ya ha sido agregado.",
                    "Ejercicio duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Pedir número de series
        String input = JOptionPane.showInputDialog(this, "Ingrese el número de series para el ejercicio " + ejercicioSeleccionado);
        if (input == null || input.trim().isEmpty()) return; // Cancelado o vacío

        int series;
        try {
            series = Integer.parseInt(input.trim());
            if (series <= 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido de series.",
                    "Entrada inválida", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar y agregar el ejercicio correspondiente
        for (Ejercicios ej : DatosGenerales.ejerciciosMap.values()) {
            if (ej.getNombre().equals(ejercicioSeleccionado)) {
                listaEjerciciosSeleccionados.add(ej);
                break;
            }
        }

        // Agregar a la tabla
        DefaultTableModel model = (DefaultTableModel) TEjerciciosS.getModel();
        model.addRow(new Object[]{ejercicioSeleccionado, series});
    }//GEN-LAST:event_btnSEActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = TEjerciciosS.getSelectedRow();

        if (filaSeleccionada != -1) {
            DefaultTableModel model = (DefaultTableModel) TEjerciciosS.getModel();
            String nombreEjercicio = (String) model.getValueAt(filaSeleccionada, 0); // Suponiendo que la columna 0 es el nombre del ejercicio

            // Eliminar de la listaEjerciciosSeleccionados usando Iterator
            Iterator<Ejercicios> iterator = listaEjerciciosSeleccionados.iterator();
            while (iterator.hasNext()) {
                Ejercicios ej = iterator.next();
                if (ej.getNombre().equals(nombreEjercicio)) {
                    iterator.remove();
                    break; // Solo elimina la primera coincidencia
                }
            }

            // Eliminar del modelo de la tabla
            model.removeRow(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    public static List<Ejercicios>listaEjerciciosSeleccionados=new ArrayList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TEjerciciosS;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSC;
    private javax.swing.JButton btnSE;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxEjercicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
